# Site settings
author: Kayla Reopelle
title: Kayla Reopelle | Junior Software Developer
header-img: img/home-bg.png
email: kreopelle@gmail.com
copyright_name: Kayla Reopelle
description: > # this means to ignore newlines until "baseurl:"
  Learning to code with the Flatiron School
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  kreopelle

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
